### ISSUE TITLE
ValueError while running mdc_neighborhoods.py

### ISSUE THREAD

**Issue by accibio** [gph82/mdciao#48]
**Hi. I have a protein-ligand complex and I'm trying to visualize the distances between ALA26 residue from the ligand and its neighboring residues (within 6 Angstroms) from the receptor.**

`mdc_neighborhoods.py prod.pdb prod.xtc -r ALA26 -co 6 -fr chains --fragment_names Receptor,Ligand --graphic_dpi 600 -nsf -tx txt -gx jpg -od . -d --n_jobs 8
` 

**But it throws this error. I'm not able to figure out what's causing the error. Please help.**

```
Will compute contact frequencies for (1 items):
prod.xtc
 with a stride of 1 frames
Using method 'chains' these fragments were found
fragment      0 with    106 AAs     PRO1 (   0) -   TYR106 (105 ) (0) 
fragment      1 with     60 AAs     ASP1 ( 106) -    ARG60 (165 ) (1) 
/home/abhishek/.local/lib/python3.10/site-packages/mdciao/utils/residue_and_atom.py:263: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  residxs_out = _pandas_unique(residxs_out)

Will compute neighborhoods for the residues
ALA26
excluding 4 nearest neighbors

   residue      residx    fragment      resSeq
     ALA26         131           1          26

Pre-computing likely neighborhoods by reducing the neighbor-list
to those within 15 Angstrom in the first frame of reference geom
'prod.pdb':...done!
Traceback (most recent call last):
  File "/home/abhishek/.local/bin/mdc_neighborhoods.py", line 43, in <module>
    out_dict = residue_neighborhoods(a.residues, a.trajectories, **b)
  File "/home/abhishek/.local/lib/python3.10/site-packages/mdciao/cli/cli.py", line 937, in residue_neighborhoods
    _, ctc_idxs_small = _md.compute_contacts(refgeom, ctc_idxs[ctc_idxs_small])
  File "/home/abhishek/.local/lib/python3.10/site-packages/mdtraj/geometry/contact.py", line 213, in compute_contacts
    atom_distances = md.compute_distances(traj, atom_pairs, periodic=periodic)
  File "/home/abhishek/.local/lib/python3.10/site-packages/mdtraj/geometry/distance.py", line 149, in compute_distances
    return compute_distances_core(
  File "/home/abhishek/.local/lib/python3.10/site-packages/mdtraj/geometry/distance.py", line 76, in compute_distances_core
    pairs = ensure_type(atom_pairs, dtype=np.int32, ndim=2, name='atom_pairs', shape=(None, 2), warn_on_cast=False)
  File "/home/abhishek/.local/lib/python3.10/site-packages/mdtraj/utils/validation.py", line 122, in ensure_type
    raise ValueError(("%s must be ndim %s. "
ValueError: atom_pairs must be ndim 2. You supplied 1
```

**Comment by gph82** [comment]
Hi, thanks for submitting this. It's possible this might be a bug. Could please upload the files and I'll double check? 

Can you please check which mdciao version you are using? 

Thanks!

**Comment by accibio** [comment]
I'm using version 0.0.6.

The files are here: [mdciao.zip](https://github.com/gph82/mdciao/files/14556025/mdciao.zip)

**Comment by gph82** [comment]
Hi, 

- Short version:
  you can repeat your command but with a ridiculously high ```--nlist_cutoff_Ang``` value, e.g.:
`mdc_neighborhoods.py prod.pdb prod.xtc -r ALA26 -co 6 -fr chains --fragment_names Receptor,Ligand --graphic_dpi 600 -nsf -tx txt -gx jpg -od . -d --nlist_cutoff_Ang 100000`
 And it will work no problem
 - Long version: 
    - mdciao makes a guess of the potential contacts using ```--nlist_cutoff_Ang```  to create a neighborlist ([from the docs](https://proteinformatics.uni-leipzig.de/mdciao/cli_cli/mdc_neighborhoods.html#Named%20Arguments)):
      ```
       --nlist_cutoff_Ang NLIST_CUTOFF_ANG
                        Cutoff for the initial neighborlist. Only atoms that
                        are within this distance in the original reference
                        (the topology file) are considered potential neighbors
                        of the --residues, s.t. non-necessary distances (e.g.
                        between the receptor's N-terminus and G-protein) are
                        not even computed. Default is 15 Angstrom.
      ```

     -  In your case, the  `original reference` is the file `prod.pdb`. Please note, both fragments of your topology are quite far apart in that file. No residues of chain 0 (blue) are within 15 Angstrom of ALA26 (licorice), so the neighborlist for potential contacts is empty.  mdciao fails because there's no contacts to compute. **The error message should be more informative**
     - The ```--nlist_cutoff_Ang``` will disappear (or behave very differently) in the upcoming version of mdciao, to avoid situations like this.
     - Please note that your reference topology `prod.pdb` contains a geometry quite different from the first geometry in `prod.xtc`. If I'm understanding correctly, your two-component system starts associated and then dissociates during simulation. The geometry in `prod.pdb` is somewhere in between these states.
     - Also, as a side note, your simulation box might be a bit small. Chain 0 (blue) could have contacts with both periodic images of chain 1 (red) simultaneously (e.g. by some minor unfolding of the termini would be enougth). Simulation boxes should in principle be big enough to accommodate.
     
In any case, thank you very much for submitting an issue :) 

Hope the above suggestion helps you keep using mdciao. There's going to be a release soon, so stay tuned.

![image](https://github.com/gph82/mdciao/assets/7518004/578858bd-5c2a-4740-9b23-f9c5887ee6df)

**Comment by accibio** [comment]
Thanks for the detailed explanation. I extracted the first snapshot (where the two proteins are in close vicinity) from the trajectory and used it as the reference file. The initial command then works perfectly. Appreciate your help :) 
Looking forward to the new release.

**Comment by gph82** [comment]
Cool, closing the issue then!

**Comment by gph82** [comment]
Hey, the newest release (0.0.7) fixes this. If you're on python < 3.12 you can```

```
pip install mdciao
mdc_neighborhoods.py prod.pdb prod.xtc -r ALA26 -co 6 -fr chains --fragment_names Receptor,Ligand --graphic_dpi 600 -nsf -tx txt -gx jpg -od . -d -# --n_jobs 8 
```
and you'll have your results (please note i've commented out the 8 jobs, since this is only one trajectory, IDK if your actual use case uses more.

For more control over the graphics, I suggest you hop onto the API mode of mdciao from the ipython console:
```
>>> ipython 
import mdciao
# the line below is the API equivalent of your command line call of mdc_neighborhoods.py
N = mdciao.cli.residue_neighborhoods("ALA26","prod.xtc", topology="prod.pdb", ctc_cutoff_Ang=6,fragments="chains", fragment_names=["Receptor","Ligand"], graphic_dpi=600, distro=True, allow_same_fragment_ctcs=False, graphic_ext="jpg")[130]
N.plot_distance_distributions(bins="auto", ctc_cutoff_Ang=6, smooth_bw=0.1)
```
Let me know how this goes!
